### ISSUE TITLE
TypeError Line 53

### ISSUE THREAD

**Issue by monden2** [thomasDOTwtf/free_stacheltier#1]
Hi!

I am very grateful that you wrote this code! I am new to Linux/Python, and still need to figure out how everything works.

For now, I try to run your code using PYCryptoDome and Python 2.7 but I keep getting the following TypeError.

Traceback (most recent call last):
   File "free_stacheltier.py", line 53, in <module>
      t1 = d1.encrypt(buffer(b,0,8))
   File "/home/monden2/.local/lib/python2.7/site-packages/Crypto/Cipher/_mode_cbc.py", line 178, in encrypt
      c_uint8_ptr(plaintext),
   File "/home/monden2/.local/lib/python2.7/site-packages/Crypto/Util/_raw_api.py", line 243, in c_uint8_ptr
   raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <type 'buffer'> cannot be passed to C code

What can I do to resolve this issue?

**Comment by monden2** [comment]
NVM, PYCryptoDome was the culprit
